spring:
  application:
    name: hystrix-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 25001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
      # 注册多个eureka以逗号分割
#      defaultZone: http://peer1:20000/eureka/, http://peer2:30000/eureka/
  instance:
    # 每间隔5秒钟，向服务中心发送一条续约指令
    lease-expiration-duration-in-seconds: 5
    # 如果30秒内，依然没有收到续约请求，判断服务过期
    lease-renewal-interval-in-seconds: 30
# 开启feign下面的Hystrix功能
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    # 全局配置超时属性
    default:
      metrics:
        rollingStats:
          # 配置时间窗口
          timeInMilliseconds: 20000
      circuitBreaker:
        # 当在配置时间窗口内达到此数量的失败后，进行短路。默认20个
        requestVolumeThreshold: 5
        # 短路多久以后开始尝试是否恢复，默认5s
        sleepWindowInMilliseconds: 8
        # 出错百分比阈值，当达到此阈值后，开始短路。默认50%
        errorThresholdPercentage: 50
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            # 超时时间
            timeoutInMilliseconds: 5000
            # 超时之后终止线程
            interruptOnTimeout: true
            # 取消的时候终止线程
            interruptOnFutureCancel: true
feign-client:
  ribbon:
    # 每台机器最大重试次数
    MaxAutoRetries: 0
    # 可以再重试几台机器
    MaxAutoRetriesNextServer: 0
    # 连接超时
    ConnectTimeout: 1000
    #  业务处理超时
    ReadTimeout: 8000
    # 在所有HTTP Method 进行重试
    OkToRetryOnAllOperations: true