spring:
  application:
    name: feign-consumer-advanced
server:
  port: 22002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
      # 注册多个eureka以逗号分割
#      defaultZone: http://peer1:20000/eureka/, http://peer2:30000/eureka/
  instance:
    # 每间隔5秒钟，向服务中心发送一条续约指令
    lease-expiration-duration-in-seconds: 5
    # 如果30秒内，依然没有收到续约请求，判断服务过期
    lease-renewal-interval-in-seconds: 30

feign-client:
  ribbon:
    # 每台机器最大重试次数
    MaxAutoRetries: 2
    # 可以再重试几台机器
    MaxAutoRetriesNextServer: 2
    # 连接超时
    ConnectTimeout: 1000
    #  业务处理超时
    ReadTimeout: 2000
    # 在所有HTTP Method 进行重试
    OkToRetryOnAllOperations: true