spring:
  application:
    name: eureka-server-peer2
server:
  port: 30000
eureka:
  instance:
    #  修改host
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer1:20000/eureka/
      #是否将自己注册到Eureka-Server中，默认的为true
      register-with-eureka: false
      #是否从Eureka-Server中获取服务注册信息，默认为true
      fetch-registry: false